// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
 
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Supporta sia VITE_SUPABASE_ANON_KEY (Netlify) che VITE_SUPABASE_PUBLISHABLE_KEY (Lovable)
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
 
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
 
